name = "kynsonszetau"
pages_build_output_dir = "public"
compatibility_date = "2021-11-02"

[vars]
NODE_VERSION = "14.19.0"

[[kv_namespaces]]
binding = "ABOUT_CONTENT_CACHE"
id = "b51c40ca4df74b518ba01386f7464410"

[env.production]
compatibility_date = "2024-12-29"

[env.production.vars]
NODE_VERSION = "16.13.0"

