// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
  DYNAMIC_CONTENT: KVNamespace;
  NOTIFICATION_WEBHOOK_URL: string;
  TURNSTILE_SECRET: string;
  TURNSTILE_SITEKEY: string;
}
