// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
  APP_ID: string;
  PRIVATE_KEY: string;
  WEBHOOK_SECRET: string;
  INSTALLATION_ID: string;
  CONTENT: KVNamespace;
}
